---
controller_hosts:
 - name: servera
   inventory: Demo Inventory2
   variables:
     ansible_host: 192.168.0.230
 - name: serverd
   inventory: Demo Inventory2
   variables:
     ansible_host: 192.168.0.235
...
